definitions:
  dto.CreateNotification:
    properties:
      channel:
        $ref: '#/definitions/shared.Channel'
      contact:
        type: string
      device_reference:
        maxLength: 38
        minLength: 32
        type: string
      message_body:
        type: string
      subject:
        type: string
      user_reference:
        maxLength: 38
        minLength: 32
        type: string
    required:
    - channel
    - contact
    - device_reference
    - message_body
    - subject
    - user_reference
    type: object
  helper.ErrorResponse:
    properties:
      code:
        type: integer
      error_reference:
        type: string
      error_type:
        type: string
      errors:
        items:
          type: string
        type: array
      timestamp:
        type: string
    type: object
  shared.Channel:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - Sms
    - Email
    - Sms_Email
info:
  contact: {}
paths:
  /api/notification:
    post:
      consumes:
      - application/json
      description: Create an Notification
      parameters:
      - description: Notification request body
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/dto.CreateNotification'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.ErrorResponse'
      summary: Create Notification
      tags:
      - Notification
  /api/notification/{reference}:
    get:
      consumes:
      - application/json
      description: Retrieve the notification by reference
      parameters:
      - description: Reference
        in: path
        name: Reference
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.ErrorResponse'
      summary: Get Notification by reference
      tags:
      - Notification
  /api/notification/device/{device_reference}/{page}:
    get:
      consumes:
      - application/json
      description: Retrieve the Notification list for a user's device
      parameters:
      - description: Device Reference
        in: path
        name: device_reference
        required: true
        type: string
      - description: Page
        in: path
        name: page
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.ErrorResponse'
      summary: Get Notification list by user device reference
      tags:
      - Notification
  /api/notification/user/{user_reference}/{page}:
    get:
      consumes:
      - application/json
      description: Retrieve the Notification list for a user
      parameters:
      - description: User Reference
        in: path
        name: user_reference
        required: true
        type: string
      - description: Page
        in: path
        name: device_reference
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.ErrorResponse'
      summary: Get Notification list by user reference
      tags:
      - Notification
swagger: "2.0"
